In [1]:
from utils.context_data_csv import ContextDataCSV
from utils.matrix_optimizer import MatrixOptimizer
import utils.sulfur.constant as const

In [2]:
obj = ContextDataCSV(const.ANIMAL_NAMES[0], 'HC1')
df = obj.data_frame
df

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C773,C774,C775,C776,C777,C778,C779,C780,C781,C782
0,0.000000,0.00000,3.680408,418.81700,0.00000,66.53958,0.00000,0.00000,196.533000,155.8137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000000,0.00000,86.177220,377.89240,17.72891,71.31065,93.87448,0.00000,178.286800,180.5938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13.303060,0.00000,90.272780,340.96680,38.86711,84.73586,87.25081,0.00000,161.734000,169.4722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54.611830,0.00000,100.103700,368.81050,36.07114,94.46078,81.09448,0.00000,146.717400,186.8772,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,48.948390,0.00000,117.283700,332.77230,33.47630,95.08051,75.37254,0.00000,133.094400,175.3686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105,10.457570,61.66214,79.681400,35.08579,81.41830,73.37283,155.45070,67.67488,0.840708,129.0375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6106,9.373077,162.94090,72.551480,31.65731,89.30545,63.71841,179.48470,61.54247,0.755739,121.0908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6107,8.401056,147.93350,66.058910,28.56385,82.88110,55.33430,197.19700,71.03745,0.678656,113.6336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6108,7.529835,134.30830,60.146720,25.77267,76.91890,48.05336,219.83540,64.60033,40.280850,106.6355,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6109,6.748962,121.93810,54.763020,23.25422,71.38560,41.73044,204.32400,58.74652,61.812810,100.0685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
MatrixOptimizer(df).divide_sd()

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C773,C774,C775,C776,C777,C778,C779,C780,C781,C782
0,0.000000,0.000000,0.065153,2.650015,0.000000,0.830542,0.000000,0.000000,6.875902,1.300062,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000000,0.000000,1.525563,2.391069,0.296638,0.890094,0.480551,0.000000,6.237541,1.506820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.133531,0.000000,1.598065,2.157427,0.650319,1.057666,0.446644,0.000000,5.658424,1.414025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.548174,0.000000,1.772098,2.333605,0.603537,1.179052,0.415129,0.000000,5.133054,1.559247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.491326,0.000000,2.076229,2.105577,0.560121,1.186787,0.385838,0.000000,4.656440,1.463222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105,0.104969,0.994487,1.410570,0.222001,1.362280,0.915834,0.795764,1.621210,0.029413,1.076650,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6106,0.094084,2.627911,1.284351,0.200308,1.494246,0.795328,0.918796,1.474303,0.026440,1.010345,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6107,0.084327,2.385871,1.169416,0.180734,1.386755,0.690678,1.009467,1.701764,0.023743,0.948124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6108,0.075582,2.166124,1.064755,0.163074,1.286996,0.599798,1.125355,1.547557,1.409265,0.889734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6109,0.067744,1.966618,0.969449,0.147138,1.194414,0.520876,1.045950,1.407324,2.162582,0.834941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN