In [9]:
from utils.context_data_csv import ContextDataCSV
from utils.matrix_optimizer import MatrixOptimizer
import utils.sulfur.constant as const

In [10]:
obj = ContextDataCSV(const.ANIMAL_NAMES[0], 'HC1')
df = obj.data_frame
df

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C773,C774,C775,C776,C777,C778,C779,C780,C781,C782
0,0.000000,0.00000,3.680408,418.81700,0.00000,66.53958,0.00000,0.00000,196.533000,155.8137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000000,0.00000,86.177220,377.89240,17.72891,71.31065,93.87448,0.00000,178.286800,180.5938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13.303060,0.00000,90.272780,340.96680,38.86711,84.73586,87.25081,0.00000,161.734000,169.4722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54.611830,0.00000,100.103700,368.81050,36.07114,94.46078,81.09448,0.00000,146.717400,186.8772,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,48.948390,0.00000,117.283700,332.77230,33.47630,95.08051,75.37254,0.00000,133.094400,175.3686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105,10.457570,61.66214,79.681400,35.08579,81.41830,73.37283,155.45070,67.67488,0.840708,129.0375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6106,9.373077,162.94090,72.551480,31.65731,89.30545,63.71841,179.48470,61.54247,0.755739,121.0908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6107,8.401056,147.93350,66.058910,28.56385,82.88110,55.33430,197.19700,71.03745,0.678656,113.6336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6108,7.529835,134.30830,60.146720,25.77267,76.91890,48.05336,219.83540,64.60033,40.280850,106.6355,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6109,6.748962,121.93810,54.763020,23.25422,71.38560,41.73044,204.32400,58.74652,61.812810,100.0685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
MatrixOptimizer(df).normalized()

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C773,C774,C775,C776,C777,C778,C779,C780,C781,C782
0,-0.717323,-1.502428,-1.643164,1.823482,-1.444224,-0.097222,-1.065280,-1.642141,5.008914,0.599413,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.717323,-1.502428,-0.182754,1.564536,-1.147586,-0.037670,-0.584730,-1.642141,4.370553,0.806170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.583792,-1.502428,-0.110252,1.330894,-0.793905,0.129902,-0.618637,-1.642141,3.791437,0.713375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.169149,-1.502428,0.063781,1.507072,-0.840686,0.251288,-0.650151,-1.642141,3.266066,0.858597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.225997,-1.502428,0.367912,1.279044,-0.884103,0.259023,-0.679442,-1.642141,2.789452,0.762573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105,-0.612354,-0.507941,-0.297747,-0.604532,-0.081944,-0.011930,-0.269516,-0.020930,-1.837575,0.376000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6106,-0.623240,1.125483,-0.423966,-0.626225,0.050023,-0.132436,-0.146484,-0.167838,-1.840547,0.309695,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6107,-0.632997,0.883443,-0.538901,-0.645799,-0.057469,-0.237086,-0.055813,0.059623,-1.843244,0.247475,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6108,-0.641742,0.663696,-0.643562,-0.663459,-0.157227,-0.327966,0.060074,-0.094584,-0.457722,0.189085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6109,-0.649580,0.464190,-0.738868,-0.679395,-0.249810,-0.406888,-0.019330,-0.234817,0.295595,0.134292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN